package io.helidon.atp.lab.service;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import io.helidon.atp.lab.entity.Dept;
import io.helidon.atp.lab.entity.DeptExample;

public interface DeptService {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table DEPT
	 *
	 * @mbg.generated Thu May 16 21:51:42 EDT 2019
	 */
	long countByExample(DeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table DEPT
	 *
	 * @mbg.generated Thu May 16 21:51:42 EDT 2019
	 */
	int deleteByExample(DeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table DEPT
	 *
	 * @mbg.generated Thu May 16 21:51:42 EDT 2019
	 */
	int insert(Dept record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table DEPT
	 *
	 * @mbg.generated Thu May 16 21:51:42 EDT 2019
	 */
	int insertSelective(Dept record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table DEPT
	 *
	 * @mbg.generated Thu May 16 21:51:42 EDT 2019
	 */
	List<Dept> selectByExample(DeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table DEPT
	 *
	 * @mbg.generated Thu May 16 21:51:42 EDT 2019
	 */
	int updateByExampleSelective(@Param("record") Dept record, @Param("example") DeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table DEPT
	 *
	 * @mbg.generated Thu May 16 21:51:42 EDT 2019
	 */
	int updateByExample(@Param("record") Dept record, @Param("example") DeptExample example);
}