package io.helidon.atp.lab.service;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import io.helidon.atp.lab.entity.Emp;
import io.helidon.atp.lab.entity.EmpExample;

public interface EmpService {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EMP
	 *
	 * @mbg.generated Thu May 16 21:51:42 EDT 2019
	 */
	long countByExample(EmpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EMP
	 *
	 * @mbg.generated Thu May 16 21:51:42 EDT 2019
	 */
	int deleteByExample(EmpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EMP
	 *
	 * @mbg.generated Thu May 16 21:51:42 EDT 2019
	 */
	int insert(Emp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EMP
	 *
	 * @mbg.generated Thu May 16 21:51:42 EDT 2019
	 */
	int insertSelective(Emp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EMP
	 *
	 * @mbg.generated Thu May 16 21:51:42 EDT 2019
	 */
	List<Emp> selectByExample(EmpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EMP
	 *
	 * @mbg.generated Thu May 16 21:51:42 EDT 2019
	 */
	int updateByExampleSelective(@Param("record") Emp record, @Param("example") EmpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EMP
	 *
	 * @mbg.generated Thu May 16 21:51:42 EDT 2019
	 */
	int updateByExample(@Param("record") Emp record, @Param("example") EmpExample example);
}