package io.helidon.atp.lab.service;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import io.helidon.atp.lab.entity.Manager;
import io.helidon.atp.lab.entity.ManagerExample;

public interface ManagerService {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MANAGER
	 *
	 * @mbg.generated Thu May 16 05:04:08 EDT 2019
	 */
	long countByExample(ManagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MANAGER
	 *
	 * @mbg.generated Thu May 16 05:04:08 EDT 2019
	 */
	int deleteByExample(ManagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MANAGER
	 *
	 * @mbg.generated Thu May 16 05:04:08 EDT 2019
	 */
	int insert(Manager record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MANAGER
	 *
	 * @mbg.generated Thu May 16 05:04:08 EDT 2019
	 */
	int insertSelective(Manager record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MANAGER
	 *
	 * @mbg.generated Thu May 16 05:04:08 EDT 2019
	 */
	List<Manager> selectByExample(ManagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MANAGER
	 *
	 * @mbg.generated Thu May 16 05:04:08 EDT 2019
	 */
	int updateByExampleSelective(@Param("record") Manager record, @Param("example") ManagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MANAGER
	 *
	 * @mbg.generated Thu May 16 05:04:08 EDT 2019
	 */
	int updateByExample(@Param("record") Manager record, @Param("example") ManagerExample example);
}