package io.helidon.atp.lab.entity;

public class Dept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPT.DEPTNO
     *
     * @mbg.generated Thu May 16 21:51:42 EDT 2019
     */
    private Short deptno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPT.DNAME
     *
     * @mbg.generated Thu May 16 21:51:42 EDT 2019
     */
    private String dname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPT.LOC
     *
     * @mbg.generated Thu May 16 21:51:42 EDT 2019
     */
    private String loc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPT.DEPTNO
     *
     * @return the value of DEPT.DEPTNO
     *
     * @mbg.generated Thu May 16 21:51:42 EDT 2019
     */
    public Short getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPT.DEPTNO
     *
     * @param deptno the value for DEPT.DEPTNO
     *
     * @mbg.generated Thu May 16 21:51:42 EDT 2019
     */
    public void setDeptno(Short deptno) {
        this.deptno = deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPT.DNAME
     *
     * @return the value of DEPT.DNAME
     *
     * @mbg.generated Thu May 16 21:51:42 EDT 2019
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPT.DNAME
     *
     * @param dname the value for DEPT.DNAME
     *
     * @mbg.generated Thu May 16 21:51:42 EDT 2019
     */
    public void setDname(String dname) {
        this.dname = dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPT.LOC
     *
     * @return the value of DEPT.LOC
     *
     * @mbg.generated Thu May 16 21:51:42 EDT 2019
     */
    public String getLoc() {
        return loc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPT.LOC
     *
     * @param loc the value for DEPT.LOC
     *
     * @mbg.generated Thu May 16 21:51:42 EDT 2019
     */
    public void setLoc(String loc) {
        this.loc = loc;
    }
}