package io.helidon.atp.lab.entity;

public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER.EMPLOYEE_ID
     *
     * @mbg.generated Thu May 16 05:04:08 EDT 2019
     */
    private String employeeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MANAGER.EMPLOYEE_ID
     *
     * @return the value of MANAGER.EMPLOYEE_ID
     *
     * @mbg.generated Thu May 16 05:04:08 EDT 2019
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MANAGER.EMPLOYEE_ID
     *
     * @param employeeId the value for MANAGER.EMPLOYEE_ID
     *
     * @mbg.generated Thu May 16 05:04:08 EDT 2019
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
}